import { useState } from 'react';
import { MessageSquare, Sparkles, Copy, Check } from 'lucide-react';
import { triggerSupportCard } from '../components/ui/SupportCard';

export function AiCommits() {
  const [diff, setDiff] = useState('');
  const [commitMessage, setCommitMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateCommit = () => {
    setLoading(true);
    // Mock generation
    setTimeout(() => {
      let type = 'chore';
      if (diff.includes('function') || diff.includes('class')) type = 'feat';
      if (diff.includes('fix') || diff.includes('error')) type = 'fix';
      
      setCommitMessage(`${type}: update implementation based on diff\n\n- Improved code structure\n- Handled edge cases\n\nGenerated by AI Commits.`);
      setLoading(false);
      triggerSupportCard();
    }, 1500);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(commitMessage);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">AI Commit Generator</h1>
        <p className="text-github-text">Paste your git diff to generate conventional commit messages.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div className="flex flex-col h-[500px] rounded-xl border border-github-border bg-github-canvas overflow-hidden">
          <div className="bg-github-border/50 px-4 py-2 border-b border-github-border text-sm font-medium text-white">
            Git Diff
          </div>
          <textarea
            value={diff}
            onChange={(e) => setDiff(e.target.value)}
            placeholder="Paste your git diff here..."
            className="flex-1 w-full resize-none bg-transparent p-4 text-github-text font-mono text-sm focus:outline-none"
            spellCheck="false"
          />
          <div className="p-4 border-t border-github-border">
            <button
              onClick={generateCommit}
              disabled={!diff || loading}
              className="w-full flex justify-center items-center gap-2 rounded-md bg-github-link px-4 py-2 font-medium text-white hover:bg-blue-600 transition-colors disabled:opacity-50"
            >
              <Sparkles className="h-4 w-4" />
              {loading ? 'Generating...' : 'Generate Commit Message'}
            </button>
          </div>
        </div>

        <div className="flex flex-col h-[500px] rounded-xl border border-github-border bg-github-canvas overflow-hidden">
          <div className="bg-github-border/50 px-4 py-2 border-b border-github-border text-sm font-medium text-white flex justify-between items-center">
            Result
            {commitMessage && (
              <button onClick={handleCopy} className="text-github-muted hover:text-white transition-colors">
                {copied ? <Check className="h-4 w-4 text-github-success" /> : <Copy className="h-4 w-4" />}
              </button>
            )}
          </div>
          <div className="flex-1 p-4">
            {commitMessage ? (
              <pre className="whitespace-pre-wrap font-mono text-sm text-github-text">
                {commitMessage}
              </pre>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-github-muted">
                <MessageSquare className="h-12 w-12 mb-4 opacity-50" />
                <p>Your AI generated message will appear here.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
